name: limitless_app
description: "A new Flutter project."
publish_to: 'none'

sdk: '>=3.0.0 <4.0.0'

environment:
  sdk: ^3.9.2

dependencies:
  extension_google_sign_in_as_googleapis_auth: ^2.0.7
  flutter:
    sdk: flutter

  http: ^1.2.0
  supabase_flutter: ^2.3.1

  provider: ^6.0.0
  
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  graphview: ^1.1.3
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  mime: ^2.0.0             
  google_fonts: ^6.1.0


  record: ^6.1.2           
  path_provider: ^2.1.2    
  permission_handler: ^12.0.1 

  googleapis: ^11.0.0       
  googleapis_auth: ^1.4.0   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png" 
  adaptive_icon_background: "#ffffff" 
  adaptive_icon_foreground: "assets/images/logo.png"
